//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPRES.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PharmacyMaster
    {
        public int PharmacyId { get; set; }

        [Required(ErrorMessage="Please provide pharmacy name", AllowEmptyStrings=false)]
        public string PharmacyName { get; set; }

        [Required(ErrorMessage = "Please provide latitude", AllowEmptyStrings = false)]
        public string Latitude { get; set; }

        [Required(ErrorMessage = "Please provide longitude", AllowEmptyStrings = false)]
        public string Longitude { get; set; }

        [Required(ErrorMessage = "Please provide location", AllowEmptyStrings = false)]
        public string Location { get; set; }

        [Required(ErrorMessage = "Please provide country", AllowEmptyStrings = false)]
        public string Country { get; set; }

        [Required(ErrorMessage = "Please provide address", AllowEmptyStrings = false)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please provide phone number", AllowEmptyStrings = false)]
        public string PhoneNum { get; set; }

        [Required(ErrorMessage = "Please provide email", AllowEmptyStrings = false)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please provide url", AllowEmptyStrings = false)]
        public string Url { get; set; }
    }
}
